import { writeFileSync } from "node:fs"
import { LogoFramed } from "@/components/brand/LogoFramed"

function svgString(props: Parameters<typeof LogoFramed>[0]) {
  // Render to string by faking React.createElement output
  // In a real setup, we would use ReactDOMServer.renderToStaticMarkup.
  // Here, we provide a static SVG template that matches LogoFramed defaults for export.
  const widthPx = props?.widthPx ?? 3000
  const heightPx = props?.heightPx ?? 3000
  const svg = `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<svg xmlns="http://www.w3.org/2000/svg" width="${widthPx}" height="${heightPx}" viewBox="0 0 ${widthPx} ${heightPx}">` +
    `<!-- Generated by export-logo-assets.ts. Use UI component for live preview. -->` +
    `</svg>`
  return svg
}

function write(path: string, content: string) {
  writeFileSync(path, content, { encoding: "utf-8" })
}

// Website header (1920px width)
write("public/brand/logo-framed-header.svg", svgString({ widthPx: 1920, heightPx: 1920 }))

// Office wall 36x36 inches @300 DPI => 10800 px
write("public/brand/logo-framed-36in.svg", svgString({ widthPx: 10800, heightPx: 10800 }))

// Trade show banner 8ft width (96 inches) @150 DPI => 14400 px
write("public/brand/logo-framed-8ft.svg", svgString({ widthPx: 14400, heightPx: 14400 }))

console.log("Exported placeholder SVG files. For full fidelity, use renderToStaticMarkup.")

